In [73]:
import pandas as pd
import numpy as np
df = pd.read_csv('weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [74]:
df.Gender = df['Gender'].replace(['Male', 'Female'], [0,1])
df.head()

Gender     Height      Weight
0       0  73.847017  241.893563
1       0  68.781904  162.310473
2       0  74.110105  212.740856
3       0  71.730978  220.042470
4       0  69.881796  206.349801

In [75]:
df.tail()

Gender     Height      Weight
8550       1  60.483946  110.565497
8551       1  63.423372  129.921671
8552       1  65.584057  155.942671
8553       1  67.429971  151.678405
8554       1  60.921791  131.253738

In [76]:
x = df.drop('Weight', axis=1)
x

Gender     Height
0          0  73.847017
1          0  68.781904
2          0  74.110105
3          0  71.730978
4          0  69.881796
...      ...        ...
8550       1  60.483946
8551       1  63.423372
8552       1  65.584057
8553       1  67.429971
8554       1  60.921791

[8555 rows x 2 columns]

In [77]:
x.shape

(8555, 2)

In [78]:
y = df['Weight']
y

0       241.893563
1       162.310473
2       212.740856
3       220.042470
4       206.349801
           ...    
8550    110.565497
8551    129.921671
8552    155.942671
8553    151.678405
8554    131.253738
Name: Weight, Length: 8555, dtype: float64

In [79]:
x.head()

Gender     Height
0       0  73.847017
1       0  68.781904
2       0  74.110105
3       0  71.730978
4       0  69.881796

In [80]:
y.head()

0    241.893563
1    162.310473
2    212.740856
3    220.042470
4    206.349801
Name: Weight, dtype: float64

In [81]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=.30, random_state = 42)

In [82]:
xtrain.head()

Gender     Height
553        0  67.594031
1397       0  71.601697
7934       1  62.625985
8367       1  66.136131
3320       0  71.843308

In [83]:
ytrain.head()

553     186.751417
1397    211.031652
7934    143.768451
8367    151.814648
3320    196.505814
Name: Weight, dtype: float64

In [84]:
xtest.head()

Gender     Height
6006       1  64.846644
1197       0  68.886367
2862       0  70.963369
6497       1  62.737189
2860       0  69.578030

In [85]:
ytest.head()

6006    149.668369
1197    197.642244
2862    178.551191
6497    141.343095
2860    195.322675
Name: Weight, dtype: float64

In [86]:
xtrain.shape

(5988, 2)

In [87]:
xtest.shape

(2567, 2)

In [88]:
ytrain.shape

(5988,)

In [89]:
ytest.shape

(2567,)

# Linear Regression

In [90]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg

LinearRegression()

In [91]:
reg.fit(xtrain, ytrain)

LinearRegression()

In [92]:
reg.coef_

array([-19.54151693,   5.9562333 ])

In [93]:
reg.intercept_

-224.25154348583987

In [94]:
training_accuracy = reg.score(xtrain, ytrain)
training_accuracy

0.8973793060969246

In [95]:
testing_accuracy = reg.score(xtest, ytest)
testing_accuracy

0.905911242442266

In [96]:
pred = reg.predict(xtest)
pred

array([142.44868114, 186.0517281 , 198.42283706, ..., 102.94080643,
       190.83713617, 143.34786753])

In [97]:
from sklearn.metrics import mean_squared_error

In [98]:
mse = mean_squared_error(ytest, pred)
mse

96.83734437830608

In [99]:
reg.score(xtest, ytest)

0.905911242442266

# KNN 

In [100]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=5)

In [101]:
knn

KNeighborsRegressor()

In [102]:
knn.fit(xtrain, ytrain)

KNeighborsRegressor()

In [103]:
pred1 = knn.predict(xtest)
pred1

array([142.1445657 , 181.38276924, 187.07075266, ..., 101.79654426,
       192.43702356, 145.3632227 ])

In [104]:
mse1 = mean_squared_error(ytest, pred1)
mse1

121.33528273624482

In [105]:
knn.score(xtest, ytest)

0.8821086423439015