In [51]:
import pandas as pd 
import numpy as np 
from matplotlib import pyplot as plt 

In [52]:
import warnings
warnings.filterwarnings("ignore")

In [53]:
df = pd.read_csv("LR_weight&price.csv")

In [54]:
df

Weight   Price
0        2     35
1        4     60
2        5     20
3        3     50
4        6     50
5        5     55
6        7     60

In [55]:
x = df.drop('Price', axis=1)
x

Weight 
0        2
1        4
2        5
3        3
4        6
5        5
6        7

In [56]:
y = df['Price']
y

0    35
1    60
2    20
3    50
4    50
5    55
6    60
Name: Price, dtype: int64

In [57]:
x.shape

(7, 1)

In [58]:
y.shape

(7,)

In [59]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [60]:
reg.fit(x,y)

LinearRegression()

In [61]:
m=reg.coef_
m

array([2.62096774])

In [62]:
c=reg.intercept_
c

35.16129032258065

In [63]:
reg.predict([[6]])

array([50.88709677])

In [64]:
pred=reg.predict(x)
pred

array([40.40322581, 45.64516129, 48.26612903, 43.02419355, 50.88709677,
       48.26612903, 53.50806452])

In [70]:
z= m*x + c
z

Weight 
0  40.403226
1  45.645161
2  48.266129
3  43.024194
4  50.887097
5  48.266129
6  53.508065

In [65]:
residuals = 50.88709677-50
residuals

0.8870967699999994

# MSE & MAE

In [68]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [69]:
mse = mean_squared_error(y,pred)
mse

167.30990783410135

In [72]:
mae = mean_absolute_error(y, pred)
mae

9.87327188940092

In [73]:
reg.score(x, y)

0.09412315095348434